mqtt:
  host: hestia.lan
  port: 1883
  keep_alive_seconds: 30
  reconnect_timeout: 60
  connection_timeout: 10
  initial_connection_attempts: 10
home_assistant:
  discovery: true
  discovery_prefix: "homeassistant"
  device_unique_id: "33564eb9"
  device_name: "BoatPi MQTT Helper"
  device_topic_prefix: "boatpi/devices"
logging:
  # filename: logfile.txt
  level: Debug
relay_control:
  - name: "Transmit AIS position"
    serial_port: 
      port: /dev/tty.usbserial-10
      baud: 9600
    guid: switch.boat_ais_transmission6ad32245
    entity_id: boat_ais_transmission
    icon: "mdi:broadcast"
signalk:
  system_id: "368327460"
  mqtt_mapping:
    - source: "zigbee2mqtt"
      format: "temperature"
      source_topic: "zigbee2mqtt/TempSensorEngineRoom"
      dest_topic: "vessels/self/environment/inside/engineRoom"
    - source: "zigbee2mqtt"
      format: "temperature"
      source_topic: "zigbee2mqtt/Cabin Temperature"
      dest_topic: "vessels/self/environment/inside/mainCabin"
    - source: "zigbee2mqtt"
      format: "temperature"
      source_topic: "zigbee2mqtt/TempSensorCockpit"
      dest_topic: "vessels/self/environment/inside/cockpit"