## Launch mqtt-relay-control config_example.yml to use this configuration file

mqtt:
  host: mqtt.lan
  port: 1883
  keep_alive_seconds: 30
  reconnect_timeout: 60
  connection_timeout: 10
  initial_connection_attempts: 10
home_assistant:
  discovery: true
  discovery_prefix: "homeassistant"
  device_unique_id: "12090asdlk"
  device_name: "BoatPi MQTT Helper"
  device_topic_prefix: "boatpi/devices"
logging:
  # filename: logfile.txt
  level: Info
relay_control:
  - name: "Transmit AIS position"
    serial_port: 
      port: /dev/tty.usbserial-10
      baud: 9600
    guid: switch.boat_ais_transmission6pap1
    entity_id: boat_ais_transmission
    icon: "mdi:broadcast"
signalk:
  system_id: "9a90a0123"
  mqtt_mapping:
    - source: "zigbee2mqtt"
      format: "temperature"
      source_topic: "zigbee2mqtt/CabinTemperature"
      dest_topic: "vessels/self/environment/inside/mainCabin"
    - source: "zigbee2mqtt"
      format: "temperature"
      source_topic: "zigbee2mqtt/CockpitTemperature"
      dest_topic: "vessels/self/environment/inside/cockpit"